# fly.toml app configuration file generated for bugtracker-backend-bold-snow-824-will on 2026-03-28T12:33:39-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bugtracker-backend-staging-sil-will'
primary_region = 'gru'

[build]

[mounts]
  source="bugtracker_data"
  destination="/data"

[env]
  DB_PATH="/data/bugs.db"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
